name: Laravel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  laravel-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install
      - name: Directory Permissions Rol
        run: chown -R root:nginx storage bootstrap/cache
      - name: Directory Permissions
        run: chmod 777 -R storage bootstrap/cache
      - name: Directory Permissions ug
        run: chmod u+w,g+w -R storage bootstrap/cache
